#!/bin/sh

BUILD_DIR_DEBUG=build-debug
BUILD_DIR_RELEASE=build-release
TOOLCHAIN_FILE=cmake/amiga-gcc-toolchain.cmake
GENERATOR="Unix Makefiles"

cmake . -B$BUILD_DIR_DEBUG -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE -G"$GENERATOR" $*
cmake . -B$BUILD_DIR_RELEASE -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE -G"$GENERATOR" $*
