_LVORLDispatch	EQU	-30
_LVOObtainDataTypeA	EQU	-36
_LVOReleaseDataType	EQU	-42
_LVONewDTObjectA	EQU	-48
_LVODisposeDTObject	EQU	-54
_LVOSetDTAttrsA	EQU	-60
_LVOGetDTAttrsA	EQU	-66
_LVOAddDTObject	EQU	-72
_LVORefreshDTObjectA	EQU	-78
_LVODoAsyncLayout	EQU	-84
_LVODoDTMethodA	EQU	-90
_LVORemoveDTObject	EQU	-96
_LVOGetDTMethods	EQU	-102
_LVOGetDTTriggerMethods	EQU	-108
_LVOPrintDTObjectA	EQU	-114
_LVOGetDTString	EQU	-138
